# Generated by Django 5.2.16 on 2026-07-09 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned')], default='CREATED', max_length=16)),
                ('reconciliation_status', models.CharField(choices=[('UNRECONCILED', 'Unreconciled'), ('MATCHED', 'Matched'), ('MISMATCHED', 'Mismatched'), ('MANUAL_REVIEW', 'Manual review')], default='UNRECONCILED', max_length=16)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='kielsync_transaction_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave')], max_length=16)),
                ('event_id', models.CharField(max_length=128)),
                ('payload', models.JSONField()),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('gateway', 'event_id'), name='kielsync_webhookevent_gateway_event_id_uniq')],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave')], max_length=16)),
                ('gateway_reference', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('REDIRECTED', 'Redirected'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='INITIATED', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_retryable', models.BooleanField(null=True)),
                ('raw_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='kielsync.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['transaction', 'created_at'], name='kielsync_attempt_txn_idx')],
            },
        ),
    ]
