# Generated by Django 5.2.16 on 2026-07-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kielsync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='gateway_reference',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
